from __future__ import annotations

TRADE_PROFILES = {
    "Electrical": {
        "sections": [
            "Main switchboards & distribution",
            "Power",
            "Lighting",
            "Emergency & exit lighting",
            "Data / communications",
            "Fire interfaces",
            "Containment",
            "External electrical",
            "Testing / commissioning",
        ],
        "units": ["No.", "point", "lm", "m", "item", "set"],
        "focus": "switchboards, circuits, outlets, switches, luminaires, emergency fittings, cable/containment routes, data points, equipment connections and testing",
        "exclude": "items clearly supplied or installed by other trades, utility authority works, equipment internals and unshown cabling routes",
    },
    "Plumbing": {
        "sections": [
            "Sanitary fixtures",
            "Cold water",
            "Hot water",
            "Sanitary drainage",
            "Stormwater",
            "Gas",
            "Pumps / plant",
            "External services",
            "Testing / commissioning",
        ],
        "units": ["No.", "point", "lm", "m", "item", "set", "L"],
        "focus": "fixtures, taps, appliances, pipework, valves, drains, pits, pumps, hot-water plant, gas services and testing",
        "exclude": "civil authority works, specialist equipment internals and services not shown or specified",
    },
    "HVAC / Mechanical": {
        "sections": [
            "Mechanical plant",
            "Ductwork",
            "Air outlets",
            "Pipework",
            "Controls",
            "Ventilation",
            "Insulation",
            "External mechanical",
            "Testing / commissioning",
        ],
        "units": ["No.", "lm", "m", "m²", "item", "set", "kg"],
        "focus": "mechanical plant, fans, grilles, diffusers, ductwork, pipework, insulation, controls, supports and commissioning",
        "exclude": "electrical supply beyond nominated interfaces, specialist plant internals and unshown routes",
    },
    "Carpentry / Joinery": {
        "sections": [
            "Structural carpentry",
            "Wall framing",
            "Roof framing",
            "Doors & frames",
            "Skirtings / architraves",
            "Internal joinery",
            "External timber",
            "Hardware",
            "Sundries",
        ],
        "units": ["No.", "lm", "m", "m²", "m³", "item", "set"],
        "focus": "timber framing, doors, frames, trims, cabinetry, joinery, battens, linings, hardware and associated carpentry",
        "exclude": "factory-supplied specialist items unless installation is in scope and work allocated to other trades",
    },
    "Plastering / Linings": {
        "sections": [
            "Wall linings",
            "Ceilings",
            "Bulkheads",
            "Wet-area linings",
            "External linings",
            "Cornices / trims",
            "Access panels",
            "Acoustic / fire systems",
            "Sundries",
        ],
        "units": ["m²", "lm", "No.", "item"],
        "focus": "plasterboard and fibre-cement linings, ceilings, bulkheads, trims, cornices, access panels, acoustic and fire-rated lining systems",
        "exclude": "paint finishes, structural framing unless explicitly included and factory-finished proprietary systems by others",
    },
    "Tiling": {
        "sections": [
            "Floor tiling",
            "Wall tiling",
            "Skirtings",
            "Splashbacks",
            "External tiling",
            "Waterproofing",
            "Movement joints",
            "Trims / edges",
            "Sundries",
        ],
        "units": ["m²", "lm", "No.", "item"],
        "focus": "floor and wall tiles, waterproofing, trims, skirtings, splashbacks, movement joints, set-outs and nominated tile finishes",
        "exclude": "substrate rectification not documented, sanitary fixtures and non-tiled finishes",
    },
    "Flooring": {
        "sections": [
            "Carpet",
            "Vinyl",
            "Timber / laminate",
            "Resilient flooring",
            "Floor preparation",
            "Skirtings / trims",
            "Stairs",
            "External flooring",
            "Sundries",
        ],
        "units": ["m²", "lm", "No.", "item"],
        "focus": "floor finishes, underlays, adhesives, floor preparation, skirtings, trims, transitions and stair finishes",
        "exclude": "structural slabs, major levelling or moisture remediation unless explicitly documented",
    },
    "Roofing": {
        "sections": [
            "Roof sheeting",
            "Flashings",
            "Gutters",
            "Downpipes",
            "Roof penetrations",
            "Insulation / sarking",
            "Roof safety",
            "Rainwater goods",
            "Sundries",
        ],
        "units": ["m²", "lm", "No.", "item", "set"],
        "focus": "roof coverings, flashings, gutters, downpipes, penetrations, insulation, sarking, roof safety and rainwater goods",
        "exclude": "structural framing, solar/electrical equipment and items allocated to other specialist trades",
    },
    "Concreting": {
        "sections": [
            "Footings",
            "Slabs",
            "Walls",
            "Columns",
            "Beams",
            "Stairs",
            "External pavements",
            "Reinforcement",
            "Formwork",
            "Sundries",
        ],
        "units": ["m³", "m²", "lm", "No.", "kg", "t", "item"],
        "focus": "concrete volumes, formwork areas, reinforcement where scheduled, joints, steps, stairs, slabs, footings, walls and external pavements",
        "exclude": "excavation, structural steel and reinforcement not measurable or scheduled in the supplied evidence",
    },
    "Landscaping": {
        "sections": [
            "Earthworks",
            "Paving",
            "Retaining",
            "Planting",
            "Turf",
            "Irrigation",
            "Fencing / screens",
            "Landscape structures",
            "External furniture",
        ],
        "units": ["m²", "m³", "lm", "No.", "item", "set"],
        "focus": "paving, soil, mulch, planting, turf, irrigation, retaining, fencing, screens, landscape structures and external furniture",
        "exclude": "civil infrastructure, authority works and items not shown in landscape drawings or specifications",
    },
    "Custom trade": {
        "sections": [
            "Primary scope",
            "Secondary scope",
            "Equipment / fixtures",
            "Materials",
            "External works",
            "Testing / completion",
            "Provisional items",
        ],
        "units": ["m²", "m³", "lm", "m", "No.", "item", "set", "kg", "t", "L", "hr", "allowance"],
        "focus": "the measurable work specifically allocated to the selected trade in the supplied drawings, schedules, specifications and scope documents",
        "exclude": "work clearly allocated to another trade or unsupported by the supplied evidence",
    },
}

TRADE_OPTIONS = list(TRADE_PROFILES)
